# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/green/BeamsizeMeasurement.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BeamsizeMeasurement(object):
    def setupUi(self, BeamsizeMeasurement):
        BeamsizeMeasurement.setObjectName("BeamsizeMeasurement")
        BeamsizeMeasurement.resize(586, 948)
        self.centralwidget = QtWidgets.QWidget(BeamsizeMeasurement)
        self.centralwidget.setObjectName("centralwidget")
        self.tbGreensFunction = QtWidgets.QLineEdit(self.centralwidget)
        self.tbGreensFunction.setGeometry(QtCore.QRect(10, 40, 471, 25))
        self.tbGreensFunction.setReadOnly(True)
        self.tbGreensFunction.setObjectName("tbGreensFunction")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 161, 17))
        self.label.setObjectName("label")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(480, 40, 89, 25))
        self.btnBrowse.setObjectName("btnBrowse")
        self.gbRadialProfile = QtWidgets.QGroupBox(self.centralwidget)
        self.gbRadialProfile.setGeometry(QtCore.QRect(10, 345, 561, 391))
        self.gbRadialProfile.setCheckable(True)
        self.gbRadialProfile.setChecked(False)
        self.gbRadialProfile.setObjectName("gbRadialProfile")
        self.label_24 = QtWidgets.QLabel(self.gbRadialProfile)
        self.label_24.setGeometry(QtCore.QRect(10, 30, 271, 121))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.tbRadialProfile = QtWidgets.QPlainTextEdit(self.gbRadialProfile)
        self.tbRadialProfile.setGeometry(QtCore.QRect(290, 30, 261, 111))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        self.tbRadialProfile.setFont(font)
        self.tbRadialProfile.setObjectName("tbRadialProfile")
        self.widgetRadialProfile = QtWidgets.QWidget(self.gbRadialProfile)
        self.widgetRadialProfile.setGeometry(QtCore.QRect(10, 150, 541, 231))
        self.widgetRadialProfile.setObjectName("widgetRadialProfile")
        self.sliderBeamsize = QtWidgets.QSlider(self.centralwidget)
        self.sliderBeamsize.setGeometry(QtCore.QRect(10, 195, 561, 24))
        self.sliderBeamsize.setMaximum(100)
        self.sliderBeamsize.setProperty("value", 100)
        self.sliderBeamsize.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBeamsize.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderBeamsize.setTickInterval(10)
        self.sliderBeamsize.setObjectName("sliderBeamsize")
        self.lblBeamsize_desc = QtWidgets.QLabel(self.centralwidget)
        self.lblBeamsize_desc.setGeometry(QtCore.QRect(10, 175, 111, 17))
        self.lblBeamsize_desc.setObjectName("lblBeamsize_desc")
        self.lblBeamsize0 = QtWidgets.QLabel(self.centralwidget)
        self.lblBeamsize0.setGeometry(QtCore.QRect(10, 220, 31, 17))
        self.lblBeamsize0.setObjectName("lblBeamsize0")
        self.lblBeamsize20 = QtWidgets.QLabel(self.centralwidget)
        self.lblBeamsize20.setGeometry(QtCore.QRect(115, 220, 31, 17))
        self.lblBeamsize20.setObjectName("lblBeamsize20")
        self.lblBeamsize40 = QtWidgets.QLabel(self.centralwidget)
        self.lblBeamsize40.setGeometry(QtCore.QRect(222, 220, 31, 17))
        self.lblBeamsize40.setObjectName("lblBeamsize40")
        self.lblBeamsize60 = QtWidgets.QLabel(self.centralwidget)
        self.lblBeamsize60.setGeometry(QtCore.QRect(332, 220, 31, 17))
        self.lblBeamsize60.setObjectName("lblBeamsize60")
        self.lblBeamsize80 = QtWidgets.QLabel(self.centralwidget)
        self.lblBeamsize80.setGeometry(QtCore.QRect(440, 220, 31, 17))
        self.lblBeamsize80.setObjectName("lblBeamsize80")
        self.lblBeamsize100 = QtWidgets.QLabel(self.centralwidget)
        self.lblBeamsize100.setGeometry(QtCore.QRect(530, 220, 41, 17))
        self.lblBeamsize100.setObjectName("lblBeamsize100")
        self.lblBeamsize = QtWidgets.QLabel(self.centralwidget)
        self.lblBeamsize.setGeometry(QtCore.QRect(366, 175, 201, 20))
        self.lblBeamsize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblBeamsize.setObjectName("lblBeamsize")
        self.lblIntensity80 = QtWidgets.QLabel(self.centralwidget)
        self.lblIntensity80.setGeometry(QtCore.QRect(438, 320, 31, 17))
        self.lblIntensity80.setObjectName("lblIntensity80")
        self.lblIntensity_desc = QtWidgets.QLabel(self.centralwidget)
        self.lblIntensity_desc.setGeometry(QtCore.QRect(8, 275, 221, 17))
        self.lblIntensity_desc.setObjectName("lblIntensity_desc")
        self.lblIntensity100 = QtWidgets.QLabel(self.centralwidget)
        self.lblIntensity100.setGeometry(QtCore.QRect(528, 320, 41, 17))
        self.lblIntensity100.setObjectName("lblIntensity100")
        self.lblIntensity40 = QtWidgets.QLabel(self.centralwidget)
        self.lblIntensity40.setGeometry(QtCore.QRect(220, 320, 31, 17))
        self.lblIntensity40.setObjectName("lblIntensity40")
        self.lblIntensity = QtWidgets.QLabel(self.centralwidget)
        self.lblIntensity.setGeometry(QtCore.QRect(364, 275, 201, 20))
        self.lblIntensity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIntensity.setObjectName("lblIntensity")
        self.sliderIntensity = QtWidgets.QSlider(self.centralwidget)
        self.sliderIntensity.setGeometry(QtCore.QRect(8, 295, 561, 24))
        self.sliderIntensity.setMinimum(0)
        self.sliderIntensity.setMaximum(100)
        self.sliderIntensity.setProperty("value", 20)
        self.sliderIntensity.setOrientation(QtCore.Qt.Horizontal)
        self.sliderIntensity.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderIntensity.setTickInterval(10)
        self.sliderIntensity.setObjectName("sliderIntensity")
        self.lblIntensity0 = QtWidgets.QLabel(self.centralwidget)
        self.lblIntensity0.setGeometry(QtCore.QRect(8, 320, 31, 17))
        self.lblIntensity0.setObjectName("lblIntensity0")
        self.lblIntensity20 = QtWidgets.QLabel(self.centralwidget)
        self.lblIntensity20.setGeometry(QtCore.QRect(113, 320, 31, 17))
        self.lblIntensity20.setObjectName("lblIntensity20")
        self.lblIntensity60 = QtWidgets.QLabel(self.centralwidget)
        self.lblIntensity60.setGeometry(QtCore.QRect(330, 320, 31, 17))
        self.lblIntensity60.setObjectName("lblIntensity60")
        self.tbOverlay = QtWidgets.QLineEdit(self.centralwidget)
        self.tbOverlay.setGeometry(QtCore.QRect(10, 765, 471, 25))
        self.tbOverlay.setReadOnly(True)
        self.tbOverlay.setObjectName("tbOverlay")
        self.btnBrowseOverlay = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowseOverlay.setGeometry(QtCore.QRect(480, 765, 89, 25))
        self.btnBrowseOverlay.setObjectName("btnBrowseOverlay")
        self.lblOverlay_desc = QtWidgets.QLabel(self.centralwidget)
        self.lblOverlay_desc.setGeometry(QtCore.QRect(10, 745, 67, 17))
        self.lblOverlay_desc.setObjectName("lblOverlay_desc")
        self.sliderOverlay = QtWidgets.QSlider(self.centralwidget)
        self.sliderOverlay.setGeometry(QtCore.QRect(10, 805, 561, 24))
        self.sliderOverlay.setMaximum(100)
        self.sliderOverlay.setProperty("value", 25)
        self.sliderOverlay.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOverlay.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderOverlay.setTickInterval(10)
        self.sliderOverlay.setObjectName("sliderOverlay")
        self.lblOverlay40 = QtWidgets.QLabel(self.centralwidget)
        self.lblOverlay40.setGeometry(QtCore.QRect(222, 830, 31, 17))
        self.lblOverlay40.setObjectName("lblOverlay40")
        self.lblOverlay0 = QtWidgets.QLabel(self.centralwidget)
        self.lblOverlay0.setGeometry(QtCore.QRect(10, 830, 31, 17))
        self.lblOverlay0.setObjectName("lblOverlay0")
        self.lblOverlay60 = QtWidgets.QLabel(self.centralwidget)
        self.lblOverlay60.setGeometry(QtCore.QRect(332, 830, 31, 17))
        self.lblOverlay60.setObjectName("lblOverlay60")
        self.lblOverlay20 = QtWidgets.QLabel(self.centralwidget)
        self.lblOverlay20.setGeometry(QtCore.QRect(115, 830, 31, 17))
        self.lblOverlay20.setObjectName("lblOverlay20")
        self.lblOverlay100 = QtWidgets.QLabel(self.centralwidget)
        self.lblOverlay100.setGeometry(QtCore.QRect(530, 830, 41, 17))
        self.lblOverlay100.setObjectName("lblOverlay100")
        self.lblOverlay80 = QtWidgets.QLabel(self.centralwidget)
        self.lblOverlay80.setGeometry(QtCore.QRect(440, 830, 31, 17))
        self.lblOverlay80.setObjectName("lblOverlay80")
        self.lblBeamRadius = QtWidgets.QLabel(self.centralwidget)
        self.lblBeamRadius.setGeometry(QtCore.QRect(10, 80, 561, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.lblBeamRadius.setFont(font)
        self.lblBeamRadius.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBeamRadius.setObjectName("lblBeamRadius")
        self.cbContour = QtWidgets.QCheckBox(self.centralwidget)
        self.cbContour.setGeometry(QtCore.QRect(10, 250, 281, 25))
        self.cbContour.setChecked(True)
        self.cbContour.setObjectName("cbContour")
        self.btnSaveImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveImage.setGeometry(QtCore.QRect(10, 860, 181, 27))
        self.btnSaveImage.setObjectName("btnSaveImage")
        self.btnSaveProfile = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveProfile.setEnabled(True)
        self.btnSaveProfile.setGeometry(QtCore.QRect(390, 860, 181, 27))
        self.btnSaveProfile.setObjectName("btnSaveProfile")
        self.btnSaveBoth = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveBoth.setEnabled(True)
        self.btnSaveBoth.setGeometry(QtCore.QRect(200, 860, 181, 27))
        self.btnSaveBoth.setObjectName("btnSaveBoth")
        BeamsizeMeasurement.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BeamsizeMeasurement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        BeamsizeMeasurement.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BeamsizeMeasurement)
        self.statusbar.setObjectName("statusbar")
        BeamsizeMeasurement.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(BeamsizeMeasurement)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(BeamsizeMeasurement)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(BeamsizeMeasurement)
        QtCore.QMetaObject.connectSlotsByName(BeamsizeMeasurement)

    def retranslateUi(self, BeamsizeMeasurement):
        _translate = QtCore.QCoreApplication.translate
        BeamsizeMeasurement.setWindowTitle(_translate("BeamsizeMeasurement", "Beam size measurement"))
        self.label.setText(_translate("BeamsizeMeasurement", "Green\'s function:"))
        self.btnBrowse.setText(_translate("BeamsizeMeasurement", "Browse"))
        self.gbRadialProfile.setTitle(_translate("BeamsizeMeasurement", "Full radial profile"))
        self.label_24.setText(_translate("BeamsizeMeasurement", "<html><head/><body><p>Negative profile values are<br/>interpreted as zero.</p><p>x         = Normalized radius<br/>a         = Beam size<br/>THETA(y)  = 0 if x &gt; y<br/>iTHETA(y) = 0 if x &lt; y</p></body></html>"))
        self.tbRadialProfile.setPlaceholderText(_translate("BeamsizeMeasurement", "Python (numpy) expression"))
        self.lblBeamsize_desc.setText(_translate("BeamsizeMeasurement", "Beam size"))
        self.lblBeamsize0.setText(_translate("BeamsizeMeasurement", "0%"))
        self.lblBeamsize20.setText(_translate("BeamsizeMeasurement", "20%"))
        self.lblBeamsize40.setText(_translate("BeamsizeMeasurement", "40%"))
        self.lblBeamsize60.setText(_translate("BeamsizeMeasurement", "60%"))
        self.lblBeamsize80.setText(_translate("BeamsizeMeasurement", "80%"))
        self.lblBeamsize100.setText(_translate("BeamsizeMeasurement", "100%"))
        self.lblBeamsize.setText(_translate("BeamsizeMeasurement", "100%"))
        self.lblIntensity80.setText(_translate("BeamsizeMeasurement", "80%"))
        self.lblIntensity_desc.setText(_translate("BeamsizeMeasurement", "Intensity threshold"))
        self.lblIntensity100.setText(_translate("BeamsizeMeasurement", "100%"))
        self.lblIntensity40.setText(_translate("BeamsizeMeasurement", "40%"))
        self.lblIntensity.setText(_translate("BeamsizeMeasurement", "0%"))
        self.lblIntensity0.setText(_translate("BeamsizeMeasurement", "0%"))
        self.lblIntensity20.setText(_translate("BeamsizeMeasurement", "20%"))
        self.lblIntensity60.setText(_translate("BeamsizeMeasurement", "60%"))
        self.btnBrowseOverlay.setText(_translate("BeamsizeMeasurement", "Browse"))
        self.lblOverlay_desc.setText(_translate("BeamsizeMeasurement", "Overlay:"))
        self.lblOverlay40.setText(_translate("BeamsizeMeasurement", "40%"))
        self.lblOverlay0.setText(_translate("BeamsizeMeasurement", "0%"))
        self.lblOverlay60.setText(_translate("BeamsizeMeasurement", "60%"))
        self.lblOverlay20.setText(_translate("BeamsizeMeasurement", "20%"))
        self.lblOverlay100.setText(_translate("BeamsizeMeasurement", "100%"))
        self.lblOverlay80.setText(_translate("BeamsizeMeasurement", "80%"))
        self.lblBeamRadius.setText(_translate("BeamsizeMeasurement", "N/A"))
        self.cbContour.setText(_translate("BeamsizeMeasurement", "Plot contour"))
        self.btnSaveImage.setText(_translate("BeamsizeMeasurement", "Save image"))
        self.btnSaveProfile.setText(_translate("BeamsizeMeasurement", "Save radial profile"))
        self.btnSaveBoth.setText(_translate("BeamsizeMeasurement", "Save both"))
        self.menuFile.setTitle(_translate("BeamsizeMeasurement", "File"))
        self.actionSave.setText(_translate("BeamsizeMeasurement", "Save as..."))
        self.actionExit.setText(_translate("BeamsizeMeasurement", "Exit"))
