# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/green/r12.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_R12(object):
    def setupUi(self, R12):
        R12.setObjectName("R12")
        R12.resize(512, 434)
        self.centralwidget = QtWidgets.QWidget(R12)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbRadiationType = QtWidgets.QComboBox(self.centralwidget)
        self.cbRadiationType.setEnabled(False)
        self.cbRadiationType.setObjectName("cbRadiationType")
        self.verticalLayout.addWidget(self.cbRadiationType)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbSumR = QtWidgets.QRadioButton(self.centralwidget)
        self.rbSumR.setChecked(True)
        self.rbSumR.setObjectName("rbSumR")
        self.horizontalLayout_2.addWidget(self.rbSumR)
        self.rbSingleR = QtWidgets.QRadioButton(self.centralwidget)
        self.rbSingleR.setChecked(False)
        self.rbSingleR.setObjectName("rbSingleR")
        self.horizontalLayout_2.addWidget(self.rbSingleR)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblWavelengthLbl = QtWidgets.QLabel(self.centralwidget)
        self.lblWavelengthLbl.setEnabled(True)
        self.lblWavelengthLbl.setObjectName("lblWavelengthLbl")
        self.horizontalLayout_8.addWidget(self.lblWavelengthLbl)
        self.lblWavelength = QtWidgets.QLabel(self.centralwidget)
        self.lblWavelength.setEnabled(True)
        self.lblWavelength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblWavelength.setObjectName("lblWavelength")
        self.horizontalLayout_8.addWidget(self.lblWavelength)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.sliderWavelength = QtWidgets.QSlider(self.centralwidget)
        self.sliderWavelength.setEnabled(True)
        self.sliderWavelength.setMaximum(5)
        self.sliderWavelength.setOrientation(QtCore.Qt.Horizontal)
        self.sliderWavelength.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderWavelength.setObjectName("sliderWavelength")
        self.verticalLayout.addWidget(self.sliderWavelength)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblRIndex = QtWidgets.QLabel(self.centralwidget)
        self.lblRIndex.setEnabled(False)
        self.lblRIndex.setObjectName("lblRIndex")
        self.horizontalLayout.addWidget(self.lblRIndex)
        self.lblR = QtWidgets.QLabel(self.centralwidget)
        self.lblR.setEnabled(False)
        self.lblR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblR.setObjectName("lblR")
        self.horizontalLayout.addWidget(self.lblR)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sliderRadius = QtWidgets.QSlider(self.centralwidget)
        self.sliderRadius.setEnabled(False)
        self.sliderRadius.setOrientation(QtCore.Qt.Horizontal)
        self.sliderRadius.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderRadius.setObjectName("sliderRadius")
        self.verticalLayout.addWidget(self.sliderRadius)
        self.gbSuper = QtWidgets.QGroupBox(self.centralwidget)
        self.gbSuper.setObjectName("gbSuper")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbSuper)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblParam1Name = QtWidgets.QLabel(self.gbSuper)
        self.lblParam1Name.setObjectName("lblParam1Name")
        self.horizontalLayout_6.addWidget(self.lblParam1Name)
        self.lblParam1 = QtWidgets.QLabel(self.gbSuper)
        self.lblParam1.setObjectName("lblParam1")
        self.horizontalLayout_6.addWidget(self.lblParam1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblParam2Name = QtWidgets.QLabel(self.gbSuper)
        self.lblParam2Name.setObjectName("lblParam2Name")
        self.horizontalLayout_7.addWidget(self.lblParam2Name)
        self.lblParam2 = QtWidgets.QLabel(self.gbSuper)
        self.lblParam2.setObjectName("lblParam2")
        self.horizontalLayout_7.addWidget(self.lblParam2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl = QtWidgets.QLabel(self.gbSuper)
        self.lbl.setObjectName("lbl")
        self.horizontalLayout_4.addWidget(self.lbl)
        self.lblSuperEnergy = QtWidgets.QLabel(self.gbSuper)
        self.lblSuperEnergy.setObjectName("lblSuperEnergy")
        self.horizontalLayout_4.addWidget(self.lblSuperEnergy)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.gbSuper)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lblSuperPitch = QtWidgets.QLabel(self.gbSuper)
        self.lblSuperPitch.setObjectName("lblSuperPitch")
        self.horizontalLayout_5.addWidget(self.lblSuperPitch)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.gbSuper)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnMark = QtWidgets.QPushButton(self.centralwidget)
        self.btnMark.setEnabled(True)
        self.btnMark.setObjectName("btnMark")
        self.horizontalLayout_3.addWidget(self.btnMark)
        self.btnPlotRadialProfile = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlotRadialProfile.setObjectName("btnPlotRadialProfile")
        self.horizontalLayout_3.addWidget(self.btnPlotRadialProfile)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.btnSave)
        R12.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(R12)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 22))
        self.menubar.setObjectName("menubar")
        R12.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(R12)
        self.statusbar.setObjectName("statusbar")
        R12.setStatusBar(self.statusbar)

        self.retranslateUi(R12)
        QtCore.QMetaObject.connectSlotsByName(R12)

    def retranslateUi(self, R12):
        _translate = QtCore.QCoreApplication.translate
        R12.setWindowTitle(_translate("R12", "Super particle viewer"))
        self.rbSumR.setText(_translate("R12", "Sum all radii"))
        self.rbSingleR.setText(_translate("R12", "Individual radii"))
        self.lblWavelengthLbl.setText(_translate("R12", "Wavelength"))
        self.lblWavelength.setText(_translate("R12", "[Wavelength]"))
        self.lblRIndex.setText(_translate("R12", "[Index]"))
        self.lblR.setText(_translate("R12", "[Radius]"))
        self.gbSuper.setTitle(_translate("R12", "Super particle"))
        self.lblParam1Name.setText(_translate("R12", "Parameter 1"))
        self.lblParam1.setText(_translate("R12", "n/a"))
        self.lblParam2Name.setText(_translate("R12", "Parameter 2"))
        self.lblParam2.setText(_translate("R12", "n/a"))
        self.lbl.setText(_translate("R12", "Energy:"))
        self.lblSuperEnergy.setText(_translate("R12", "n/a"))
        self.label_2.setText(_translate("R12", "Pitch angle:"))
        self.lblSuperPitch.setText(_translate("R12", "n/a"))
        self.btnMark.setText(_translate("R12", "Mark super-particle"))
        self.btnPlotRadialProfile.setText(_translate("R12", "Plot radial profile"))
        self.btnSave.setText(_translate("R12", "Save figure"))
