# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/distfunc_anapitch.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DistributionFunctionAnalysePitch(object):
    def setupUi(self, DistributionFunctionAnalysePitch):
        DistributionFunctionAnalysePitch.setObjectName("DistributionFunctionAnalysePitch")
        DistributionFunctionAnalysePitch.resize(852, 704)
        DistributionFunctionAnalysePitch.setSizeGripEnabled(True)
        DistributionFunctionAnalysePitch.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(DistributionFunctionAnalysePitch)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetPlot = QtWidgets.QWidget(DistributionFunctionAnalysePitch)
        self.widgetPlot.setObjectName("widgetPlot")
        self.verticalLayout.addWidget(self.widgetPlot)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(DistributionFunctionAnalysePitch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lblMomentum = QtWidgets.QLabel(DistributionFunctionAnalysePitch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMomentum.sizePolicy().hasHeightForWidth())
        self.lblMomentum.setSizePolicy(sizePolicy)
        self.lblMomentum.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMomentum.setObjectName("lblMomentum")
        self.horizontalLayout_2.addWidget(self.lblMomentum)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.sliderMomentum = QtWidgets.QSlider(DistributionFunctionAnalysePitch)
        self.sliderMomentum.setMaximum(1000)
        self.sliderMomentum.setOrientation(QtCore.Qt.Horizontal)
        self.sliderMomentum.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderMomentum.setTickInterval(100)
        self.sliderMomentum.setObjectName("sliderMomentum")
        self.verticalLayout.addWidget(self.sliderMomentum)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gbAnalysis = QtWidgets.QGroupBox(DistributionFunctionAnalysePitch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbAnalysis.sizePolicy().hasHeightForWidth())
        self.gbAnalysis.setSizePolicy(sizePolicy)
        self.gbAnalysis.setMinimumSize(QtCore.QSize(0, 200))
        self.gbAnalysis.setObjectName("gbAnalysis")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbAnalysis)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnLogPlot = QtWidgets.QPushButton(self.gbAnalysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLogPlot.sizePolicy().hasHeightForWidth())
        self.btnLogPlot.setSizePolicy(sizePolicy)
        self.btnLogPlot.setObjectName("btnLogPlot")
        self.verticalLayout_2.addWidget(self.btnLogPlot)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_4.addWidget(self.gbAnalysis)
        self.gbFit = QtWidgets.QGroupBox(DistributionFunctionAnalysePitch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbFit.sizePolicy().hasHeightForWidth())
        self.gbFit.setSizePolicy(sizePolicy)
        self.gbFit.setCheckable(True)
        self.gbFit.setChecked(False)
        self.gbFit.setObjectName("gbFit")
        self.label_2 = QtWidgets.QLabel(self.gbFit)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 31, 19))
        self.label_2.setObjectName("label_2")
        self.lblExpFit = QtWidgets.QLabel(self.gbFit)
        self.lblExpFit.setGeometry(QtCore.QRect(50, 30, 91, 19))
        self.lblExpFit.setObjectName("lblExpFit")
        self.horizontalLayout_4.addWidget(self.gbFit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnClose = QtWidgets.QPushButton(DistributionFunctionAnalysePitch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
        self.btnClose.setSizePolicy(sizePolicy)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(DistributionFunctionAnalysePitch)
        self.btnClose.clicked.connect(DistributionFunctionAnalysePitch.close)
        QtCore.QMetaObject.connectSlotsByName(DistributionFunctionAnalysePitch)

    def retranslateUi(self, DistributionFunctionAnalysePitch):
        _translate = QtCore.QCoreApplication.translate
        DistributionFunctionAnalysePitch.setWindowTitle(_translate("DistributionFunctionAnalysePitch", "Analyse pitch distribution"))
        self.label.setText(_translate("DistributionFunctionAnalysePitch", "Momentum (mc)"))
        self.lblMomentum.setText(_translate("DistributionFunctionAnalysePitch", "0"))
        self.gbAnalysis.setTitle(_translate("DistributionFunctionAnalysePitch", "Analysis tools"))
        self.btnLogPlot.setText(_translate("DistributionFunctionAnalysePitch", "Toggle logarithmic scale"))
        self.gbFit.setTitle(_translate("DistributionFunctionAnalysePitch", "Exponential fit"))
        self.label_2.setText(_translate("DistributionFunctionAnalysePitch", "C = "))
        self.lblExpFit.setText(_translate("DistributionFunctionAnalysePitch", "N/A"))
        self.btnClose.setText(_translate("DistributionFunctionAnalysePitch", "Close"))
