# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/image.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImageWindow(object):
    def setupUi(self, ImageWindow):
        ImageWindow.setObjectName("ImageWindow")
        ImageWindow.resize(560, 500)
        ImageWindow.setMinimumSize(QtCore.QSize(560, 500))
        ImageWindow.setMaximumSize(QtCore.QSize(560, 500))
        self.centralwidget = QtWidgets.QWidget(ImageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpen.setGeometry(QtCore.QRect(420, 10, 61, 32))
        self.btnOpen.setObjectName("btnOpen")
        self.btnReload = QtWidgets.QPushButton(self.centralwidget)
        self.btnReload.setGeometry(QtCore.QRect(483, 10, 61, 32))
        self.btnReload.setObjectName("btnReload")
        self.txtFilename = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFilename.setGeometry(QtCore.QRect(20, 10, 391, 32))
        self.txtFilename.setObjectName("txtFilename")
        self.cbPlotType = QtWidgets.QComboBox(self.centralwidget)
        self.cbPlotType.setGeometry(QtCore.QRect(100, 50, 441, 30))
        self.cbPlotType.setObjectName("cbPlotType")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 55, 71, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 95, 71, 20))
        self.label_2.setObjectName("label_2")
        self.cbColormap = QtWidgets.QComboBox(self.centralwidget)
        self.cbColormap.setGeometry(QtCore.QRect(100, 90, 441, 30))
        self.cbColormap.setObjectName("cbColormap")
        self.sliderIntensity = QtWidgets.QSlider(self.centralwidget)
        self.sliderIntensity.setGeometry(QtCore.QRect(10, 340, 531, 26))
        self.sliderIntensity.setMinimum(1)
        self.sliderIntensity.setMaximum(100)
        self.sliderIntensity.setPageStep(10)
        self.sliderIntensity.setProperty("value", 100)
        self.sliderIntensity.setTracking(True)
        self.sliderIntensity.setOrientation(QtCore.Qt.Horizontal)
        self.sliderIntensity.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderIntensity.setTickInterval(10)
        self.sliderIntensity.setObjectName("sliderIntensity")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 320, 171, 20))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 370, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(210, 370, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 370, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(420, 370, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(510, 370, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 370, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(10, 400, 94, 32))
        self.btnSave.setObjectName("btnSave")
        self.lblIntensity = QtWidgets.QLabel(self.centralwidget)
        self.lblIntensity.setGeometry(QtCore.QRect(470, 320, 63, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblIntensity.setFont(font)
        self.lblIntensity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblIntensity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblIntensity.setObjectName("lblIntensity")
        self.btnInfo = QtWidgets.QPushButton(self.centralwidget)
        self.btnInfo.setEnabled(False)
        self.btnInfo.setGeometry(QtCore.QRect(110, 400, 94, 32))
        self.btnInfo.setObjectName("btnInfo")
        self.cbColorbar = QtWidgets.QCheckBox(self.centralwidget)
        self.cbColorbar.setGeometry(QtCore.QRect(300, 190, 181, 29))
        self.cbColorbar.setObjectName("cbColorbar")
        self.cbInvert = QtWidgets.QCheckBox(self.centralwidget)
        self.cbInvert.setGeometry(QtCore.QRect(20, 220, 151, 26))
        self.cbInvert.setObjectName("cbInvert")
        self.cbRelativeColorbar = QtWidgets.QCheckBox(self.centralwidget)
        self.cbRelativeColorbar.setGeometry(QtCore.QRect(300, 220, 211, 26))
        self.cbRelativeColorbar.setObjectName("cbRelativeColorbar")
        self.cbBrightImage = QtWidgets.QCheckBox(self.centralwidget)
        self.cbBrightImage.setGeometry(QtCore.QRect(20, 190, 181, 26))
        self.cbBrightImage.setObjectName("cbBrightImage")
        self.cbTopview = QtWidgets.QCheckBox(self.centralwidget)
        self.cbTopview.setEnabled(False)
        self.cbTopview.setGeometry(QtCore.QRect(20, 250, 191, 26))
        self.cbTopview.setObjectName("cbTopview")
        self.btnWall = QtWidgets.QPushButton(self.centralwidget)
        self.btnWall.setEnabled(False)
        self.btnWall.setGeometry(QtCore.QRect(430, 400, 121, 31))
        self.btnWall.setObjectName("btnWall")
        self.cbWallCross = QtWidgets.QCheckBox(self.centralwidget)
        self.cbWallCross.setEnabled(False)
        self.cbWallCross.setGeometry(QtCore.QRect(300, 250, 231, 26))
        self.cbWallCross.setObjectName("cbWallCross")
        self.cbSeparatrix = QtWidgets.QCheckBox(self.centralwidget)
        self.cbSeparatrix.setEnabled(False)
        self.cbSeparatrix.setGeometry(QtCore.QRect(20, 280, 241, 26))
        self.cbSeparatrix.setObjectName("cbSeparatrix")
        self.cbImageType = QtWidgets.QComboBox(self.centralwidget)
        self.cbImageType.setEnabled(True)
        self.cbImageType.setGeometry(QtCore.QRect(100, 130, 441, 27))
        self.cbImageType.setObjectName("cbImageType")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 68, 20))
        self.label_4.setObjectName("label_4")
        ImageWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImageWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 24))
        self.menubar.setObjectName("menubar")
        ImageWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImageWindow)
        self.statusbar.setObjectName("statusbar")
        ImageWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ImageWindow)
        QtCore.QMetaObject.connectSlotsByName(ImageWindow)

    def retranslateUi(self, ImageWindow):
        _translate = QtCore.QCoreApplication.translate
        ImageWindow.setWindowTitle(_translate("ImageWindow", "SOFT Image Visualization"))
        self.btnOpen.setText(_translate("ImageWindow", "Open..."))
        self.btnReload.setText(_translate("ImageWindow", "Reload"))
        self.txtFilename.setPlaceholderText(_translate("ImageWindow", "Image filename"))
        self.label.setText(_translate("ImageWindow", "Plot type:"))
        self.label_2.setText(_translate("ImageWindow", "Colormap:"))
        self.label_3.setText(_translate("ImageWindow", "Maximum intensity level:"))
        self.label_5.setText(_translate("ImageWindow", "20%"))
        self.label_6.setText(_translate("ImageWindow", "40%"))
        self.label_7.setText(_translate("ImageWindow", "60%"))
        self.label_8.setText(_translate("ImageWindow", "80%"))
        self.label_9.setText(_translate("ImageWindow", "100%"))
        self.label_10.setText(_translate("ImageWindow", "0%"))
        self.btnSave.setText(_translate("ImageWindow", "Save"))
        self.lblIntensity.setText(_translate("ImageWindow", "100%"))
        self.btnInfo.setText(_translate("ImageWindow", "Show info"))
        self.cbColorbar.setText(_translate("ImageWindow", "Show colorbar"))
        self.cbInvert.setText(_translate("ImageWindow", "Invert colormap"))
        self.cbRelativeColorbar.setText(_translate("ImageWindow", "Use relative color scale"))
        self.cbBrightImage.setText(_translate("ImageWindow", "Bright image"))
        self.cbTopview.setText(_translate("ImageWindow", "Topview"))
        self.btnWall.setText(_translate("ImageWindow", "3D Wall Overlay"))
        self.cbWallCross.setText(_translate("ImageWindow", "Wall cross-section"))
        self.cbSeparatrix.setText(_translate("ImageWindow", "Separatrix"))
        self.label_4.setText(_translate("ImageWindow", "Type:"))

