# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/orbits.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Orbits(object):
    def setupUi(self, Orbits):
        Orbits.setObjectName("Orbits")
        Orbits.resize(649, 813)
        self.centralwidget = QtWidgets.QWidget(Orbits)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.tbFileName.setReadOnly(True)
        self.tbFileName.setObjectName("tbFileName")
        self.horizontalLayout.addWidget(self.tbFileName)
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gbDetails = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDetails.setObjectName("gbDetails")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbDetails)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.gbDetails)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lblNumberOfOrbits = QtWidgets.QLabel(self.gbDetails)
        self.lblNumberOfOrbits.setObjectName("lblNumberOfOrbits")
        self.horizontalLayout_2.addWidget(self.lblNumberOfOrbits)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.gbDetails)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lblFileSize = QtWidgets.QLabel(self.gbDetails)
        self.lblFileSize.setObjectName("lblFileSize")
        self.horizontalLayout_3.addWidget(self.lblFileSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.gbDetails)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lblRadialPoints = QtWidgets.QLabel(self.gbDetails)
        self.lblRadialPoints.setObjectName("lblRadialPoints")
        self.horizontalLayout_4.addWidget(self.lblRadialPoints)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblParam1Name = QtWidgets.QLabel(self.gbDetails)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblParam1Name.setFont(font)
        self.lblParam1Name.setObjectName("lblParam1Name")
        self.horizontalLayout_5.addWidget(self.lblParam1Name)
        self.lblParam1Points = QtWidgets.QLabel(self.gbDetails)
        self.lblParam1Points.setObjectName("lblParam1Points")
        self.horizontalLayout_5.addWidget(self.lblParam1Points)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblParam2Name = QtWidgets.QLabel(self.gbDetails)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblParam2Name.setFont(font)
        self.lblParam2Name.setObjectName("lblParam2Name")
        self.horizontalLayout_6.addWidget(self.lblParam2Name)
        self.lblParam2Points = QtWidgets.QLabel(self.gbDetails)
        self.lblParam2Points.setObjectName("lblParam2Points")
        self.horizontalLayout_6.addWidget(self.lblParam2Points)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label_10 = QtWidgets.QLabel(self.gbDetails)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnShowClassification = QtWidgets.QPushButton(self.gbDetails)
        self.btnShowClassification.setObjectName("btnShowClassification")
        self.horizontalLayout_7.addWidget(self.btnShowClassification)
        self.btnShowMinB = QtWidgets.QPushButton(self.gbDetails)
        self.btnShowMinB.setObjectName("btnShowMinB")
        self.horizontalLayout_7.addWidget(self.btnShowMinB)
        self.btnShowMaxB = QtWidgets.QPushButton(self.gbDetails)
        self.btnShowMaxB.setObjectName("btnShowMaxB")
        self.horizontalLayout_7.addWidget(self.btnShowMaxB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.btnShowTransitTime = QtWidgets.QPushButton(self.gbDetails)
        self.btnShowTransitTime.setObjectName("btnShowTransitTime")
        self.horizontalLayout_18.addWidget(self.btnShowTransitTime)
        self.btnShowJacobian = QtWidgets.QPushButton(self.gbDetails)
        self.btnShowJacobian.setObjectName("btnShowJacobian")
        self.horizontalLayout_18.addWidget(self.btnShowJacobian)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.verticalLayout.addWidget(self.gbDetails)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lblRadiusHS = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblRadiusHS.setFont(font)
        self.lblRadiusHS.setObjectName("lblRadiusHS")
        self.horizontalLayout_13.addWidget(self.lblRadiusHS)
        self.lblRadius = QtWidgets.QLabel(self.centralwidget)
        self.lblRadius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRadius.setObjectName("lblRadius")
        self.horizontalLayout_13.addWidget(self.lblRadius)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.hsRadius = QtWidgets.QSlider(self.centralwidget)
        self.hsRadius.setMinimumSize(QtCore.QSize(0, 25))
        self.hsRadius.setOrientation(QtCore.Qt.Horizontal)
        self.hsRadius.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hsRadius.setTickInterval(1)
        self.hsRadius.setObjectName("hsRadius")
        self.verticalLayout.addWidget(self.hsRadius)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lblParam1HS = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblParam1HS.setFont(font)
        self.lblParam1HS.setObjectName("lblParam1HS")
        self.horizontalLayout_14.addWidget(self.lblParam1HS)
        self.lblParam1 = QtWidgets.QLabel(self.centralwidget)
        self.lblParam1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblParam1.setObjectName("lblParam1")
        self.horizontalLayout_14.addWidget(self.lblParam1)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.hsParam1 = QtWidgets.QSlider(self.centralwidget)
        self.hsParam1.setMinimumSize(QtCore.QSize(0, 25))
        self.hsParam1.setOrientation(QtCore.Qt.Horizontal)
        self.hsParam1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hsParam1.setTickInterval(1)
        self.hsParam1.setObjectName("hsParam1")
        self.verticalLayout.addWidget(self.hsParam1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lblParam2HS = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblParam2HS.setFont(font)
        self.lblParam2HS.setObjectName("lblParam2HS")
        self.horizontalLayout_15.addWidget(self.lblParam2HS)
        self.lblParam2 = QtWidgets.QLabel(self.centralwidget)
        self.lblParam2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblParam2.setObjectName("lblParam2")
        self.horizontalLayout_15.addWidget(self.lblParam2)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.hsParam2 = QtWidgets.QSlider(self.centralwidget)
        self.hsParam2.setMinimumSize(QtCore.QSize(0, 25))
        self.hsParam2.setOrientation(QtCore.Qt.Horizontal)
        self.hsParam2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hsParam2.setTickInterval(1)
        self.hsParam2.setObjectName("hsParam2")
        self.verticalLayout.addWidget(self.hsParam2)
        self.gbOrbit = QtWidgets.QGroupBox(self.centralwidget)
        self.gbOrbit.setObjectName("gbOrbit")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbOrbit)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.gbOrbit)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.lblClass = QtWidgets.QLabel(self.gbOrbit)
        self.lblClass.setObjectName("lblClass")
        self.horizontalLayout_8.addWidget(self.lblClass)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.gbOrbit)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.lblMinB = QtWidgets.QLabel(self.gbOrbit)
        self.lblMinB.setObjectName("lblMinB")
        self.horizontalLayout_10.addWidget(self.lblMinB)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.gbOrbit)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.lblMaxB = QtWidgets.QLabel(self.gbOrbit)
        self.lblMaxB.setObjectName("lblMaxB")
        self.horizontalLayout_11.addWidget(self.lblMaxB)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.gbOrbit)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.lblTransitTime = QtWidgets.QLabel(self.gbOrbit)
        self.lblTransitTime.setObjectName("lblTransitTime")
        self.horizontalLayout_12.addWidget(self.lblTransitTime)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout.addWidget(self.gbOrbit)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnPlotOrbit1D = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlotOrbit1D.setObjectName("btnPlotOrbit1D")
        self.horizontalLayout_9.addWidget(self.btnPlotOrbit1D)
        self.btnPlotOrbit2D = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlotOrbit2D.setObjectName("btnPlotOrbit2D")
        self.horizontalLayout_9.addWidget(self.btnPlotOrbit2D)
        self.btnPlotOrbit3D = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlotOrbit3D.setObjectName("btnPlotOrbit3D")
        self.horizontalLayout_9.addWidget(self.btnPlotOrbit3D)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btnPlotPpar = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlotPpar.setObjectName("btnPlotPpar")
        self.horizontalLayout_16.addWidget(self.btnPlotPpar)
        self.btnPlotPperp = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlotPperp.setObjectName("btnPlotPperp")
        self.horizontalLayout_16.addWidget(self.btnPlotPperp)
        self.btnPlotPitch = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlotPitch.setObjectName("btnPlotPitch")
        self.horizontalLayout_16.addWidget(self.btnPlotPitch)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btnPlotB = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlotB.setObjectName("btnPlotB")
        self.horizontalLayout_17.addWidget(self.btnPlotB)
        self.btnPlotTime = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlotTime.setObjectName("btnPlotTime")
        self.horizontalLayout_17.addWidget(self.btnPlotTime)
        self.btnPlotJ = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlotJ.setObjectName("btnPlotJ")
        self.horizontalLayout_17.addWidget(self.btnPlotJ)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        Orbits.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Orbits)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 24))
        self.menubar.setObjectName("menubar")
        Orbits.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Orbits)
        self.statusbar.setObjectName("statusbar")
        Orbits.setStatusBar(self.statusbar)

        self.retranslateUi(Orbits)
        QtCore.QMetaObject.connectSlotsByName(Orbits)

    def retranslateUi(self, Orbits):
        _translate = QtCore.QCoreApplication.translate
        Orbits.setWindowTitle(_translate("Orbits", "SOFT Orbit Plotter"))
        self.tbFileName.setPlaceholderText(_translate("Orbits", "Name of orbit file..."))
        self.btnBrowse.setText(_translate("Orbits", "Browse..."))
        self.gbDetails.setTitle(_translate("Orbits", "Details"))
        self.label.setText(_translate("Orbits", "Number of orbits:"))
        self.lblNumberOfOrbits.setText(_translate("Orbits", "N/A"))
        self.label_2.setText(_translate("Orbits", "File size:"))
        self.lblFileSize.setText(_translate("Orbits", "N/A"))
        self.label_3.setText(_translate("Orbits", "Radial points:"))
        self.lblRadialPoints.setText(_translate("Orbits", "N/A"))
        self.lblParam1Name.setText(_translate("Orbits", "Mom. param. 1:"))
        self.lblParam1Points.setText(_translate("Orbits", "N/A"))
        self.lblParam2Name.setText(_translate("Orbits", "Mom. param. 2:"))
        self.lblParam2Points.setText(_translate("Orbits", "N/A"))
        self.label_10.setText(_translate("Orbits", "Plots"))
        self.btnShowClassification.setText(_translate("Orbits", "Classifications"))
        self.btnShowMinB.setText(_translate("Orbits", "Minimum B"))
        self.btnShowMaxB.setText(_translate("Orbits", "Maximum B"))
        self.btnShowTransitTime.setText(_translate("Orbits", "Transit time"))
        self.btnShowJacobian.setText(_translate("Orbits", "Maximum of Jacobian"))
        self.lblRadiusHS.setText(_translate("Orbits", "Radius (m)"))
        self.lblRadius.setText(_translate("Orbits", "N/A"))
        self.lblParam1HS.setText(_translate("Orbits", "Parameter 1"))
        self.lblParam1.setText(_translate("Orbits", "N/A"))
        self.lblParam2HS.setText(_translate("Orbits", "Parameter 2"))
        self.lblParam2.setText(_translate("Orbits", "N/A"))
        self.gbOrbit.setTitle(_translate("Orbits", "Selected orbit"))
        self.label_7.setText(_translate("Orbits", "Orbit classification:"))
        self.lblClass.setText(_translate("Orbits", "N/A"))
        self.label_11.setText(_translate("Orbits", "Minimum B along orbit:"))
        self.lblMinB.setText(_translate("Orbits", "N/A"))
        self.label_13.setText(_translate("Orbits", "Maximum B along orbit:"))
        self.lblMaxB.setText(_translate("Orbits", "N/A"))
        self.label_15.setText(_translate("Orbits", "Transit time:"))
        self.lblTransitTime.setText(_translate("Orbits", "N/A"))
        self.btnPlotOrbit1D.setText(_translate("Orbits", "Orbit radius"))
        self.btnPlotOrbit2D.setText(_translate("Orbits", "Orbit 2D"))
        self.btnPlotOrbit3D.setText(_translate("Orbits", "Orbit 3D"))
        self.btnPlotPpar.setText(_translate("Orbits", "Parallel momentum"))
        self.btnPlotPperp.setText(_translate("Orbits", "Perpendicular momentum"))
        self.btnPlotPitch.setText(_translate("Orbits", "Pitch"))
        self.btnPlotB.setText(_translate("Orbits", "Magnetic field strength"))
        self.btnPlotTime.setText(_translate("Orbits", "Orbit time"))
        self.btnPlotJ.setText(_translate("Orbits", "Jacobian"))
