# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sightlineMappings.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SightlineMappings(object):
    def setupUi(self, SightlineMappings):
        SightlineMappings.setObjectName("SightlineMappings")
        SightlineMappings.resize(666, 508)
        self.verticalLayout = QtWidgets.QVBoxLayout(SightlineMappings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetPlot = QtWidgets.QWidget(SightlineMappings)
        self.widgetPlot.setObjectName("widgetPlot")
        self.verticalLayout.addWidget(self.widgetPlot)
        self.groupBox = QtWidgets.QGroupBox(SightlineMappings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.tbGeometryFile = QtWidgets.QLineEdit(self.groupBox)
        self.tbGeometryFile.setReadOnly(True)
        self.tbGeometryFile.setObjectName("tbGeometryFile")
        self.horizontalLayout.addWidget(self.tbGeometryFile)
        self.btnBrowse = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblCalcStatus = QtWidgets.QLabel(self.groupBox)
        self.lblCalcStatus.setText("")
        self.lblCalcStatus.setObjectName("lblCalcStatus")
        self.horizontalLayout_5.addWidget(self.lblCalcStatus)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnCalc = QtWidgets.QPushButton(self.groupBox)
        self.btnCalc.setEnabled(False)
        self.btnCalc.setObjectName("btnCalc")
        self.horizontalLayout_2.addWidget(self.btnCalc)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnSave = QtWidgets.QPushButton(self.groupBox)
        self.btnSave.setEnabled(False)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_3.addWidget(self.btnSave)
        self.btnViewMapping = QtWidgets.QPushButton(self.groupBox)
        self.btnViewMapping.setEnabled(True)
        self.btnViewMapping.setObjectName("btnViewMapping")
        self.horizontalLayout_3.addWidget(self.btnViewMapping)
        self.btnPlotXS = QtWidgets.QPushButton(self.groupBox)
        self.btnPlotXS.setEnabled(False)
        self.btnPlotXS.setObjectName("btnPlotXS")
        self.horizontalLayout_3.addWidget(self.btnPlotXS)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnClose = QtWidgets.QPushButton(SightlineMappings)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_4.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 1)

        self.retranslateUi(SightlineMappings)
        self.btnClose.clicked.connect(SightlineMappings.close)
        QtCore.QMetaObject.connectSlotsByName(SightlineMappings)

    def retranslateUi(self, SightlineMappings):
        _translate = QtCore.QCoreApplication.translate
        SightlineMappings.setWindowTitle(_translate("SightlineMappings", "Sightline mappings"))
        self.groupBox.setTitle(_translate("SightlineMappings", "Sightline mappings"))
        self.label.setText(_translate("SightlineMappings", "Geometry file:"))
        self.btnBrowse.setText(_translate("SightlineMappings", "Browse..."))
        self.progressBar.setFormat(_translate("SightlineMappings", "%v/%m"))
        self.btnCalc.setText(_translate("SightlineMappings", "Calculate radial mapping"))
        self.btnSave.setText(_translate("SightlineMappings", "Save radial mapping"))
        self.btnViewMapping.setText(_translate("SightlineMappings", "View radial mapping"))
        self.btnPlotXS.setText(_translate("SightlineMappings", "Plot over cross-section"))
        self.btnClose.setText(_translate("SightlineMappings", "Close"))
